spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:authsvc_db}
    username: ${POSTGRES_USER:authsvc_user}
    password: ${POSTGRES_PASSWORD:ChangeMeStrongP@ssw0rd}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-init-sql: "SET TIME ZONE 'Asia/Kolkata'"
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
