spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:authsvc_db}
    username: ${POSTGRES_USER:authsvc_user}
    password: ${POSTGRES_PASSWORD:ChangeMeStrongP@ssw0rd}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-init-sql: "SET TIME ZONE 'Asia/Kolkata'"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none        # important: Flyway handles schema
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migration: true

logging:
  level:
    root: INFO
